name: Test config SHA256

permissions:
  contents: read

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y wget curl php
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: '7.0.2'
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: Install BBDown
        run: |
          dotnet tool install --global BBDown
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      - name: Show versions
        run: |
          python --version
          ffmpeg -version | head -n1
          BBDown --help --version
      - name: Test each config
        run: |
          for file in config/*.yaml; do
            echo "================================================================"
            echo "= $file"
            echo "================================================================"
            python main.py "$file"
          done
